name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Check for changes in site folder
        id: check_changes
        run: |
          changes=$(git status --porcelain)
          if [[ -n "$changes" ]]; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

      - name: Deploy static site to S3 bucket
        run: |
          if [[ "${{ steps.check_changes.outputs.changes }}" == "true" ]]; then
            aws s3 sync ./site/ s3://jg-cloud-resume-bucket --delete
          else
            echo "No changes in the site folder. Skipping deployment."
            exit 0
          fi

      - name: Create CloudFront invalidation
        if: steps.check_changes.outputs.changes == 'true'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"


